## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/

In [ ]:
print("Hello Tensor")

Hello Tensor


In [ ]:
!nvidia-smi

Tue Aug 27 21:32:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


## Introduction to Tensors

## Creating tensors
PyTorch tensors are created using torch.tensor()

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],[6,7]])
matrix

tensor([[7, 8],
        [6, 7]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([6, 7])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
type(matrix)

torch.Tensor

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],[5,4,3],[7,4,2]]])
tensor

tensor([[[1, 2, 3],
         [5, 4, 3],
         [7, 4, 2]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

### Random Tensors
Why Random Tensors? </br>
Random tensors are important because the way many neural networks lear is that they start with tensors full of random numbers and ten adjust those random number to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random number` </br>
Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1650, 0.2344, 0.9800, 0.9451],
        [0.3281, 0.8103, 0.1361, 0.5103],
        [0.3690, 0.6107, 0.0016, 0.0096]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [ ]:
random_tensor = torch.rand(1, 10,10)
random_tensor

tensor([[[0.6053, 0.2221, 0.2008, 0.5338, 0.1972, 0.9160, 0.7174, 0.7864,
          0.5037, 0.0900],
         [0.3261, 0.2132, 0.6612, 0.0378, 0.0588, 0.7379, 0.9957, 0.5056,
          0.4631, 0.2138],
         [0.7402, 0.5631, 0.4147, 0.1282, 0.0503, 0.0902, 0.3461, 0.9668,
          0.9723, 0.9537],
         [0.0904, 0.9505, 0.9048, 0.3779, 0.4772, 0.5869, 0.9333, 0.9449,
          0.8913, 0.8049],
         [0.1456, 0.4096, 0.9566, 0.8709, 0.2481, 0.7416, 0.3477, 0.7044,
          0.0442, 0.7187],
         [0.1655, 0.9322, 0.0328, 0.2798, 0.4207, 0.9358, 0.0879, 0.5988,
          0.2224, 0.9546],
         [0.8636, 0.4130, 0.1341, 0.5934, 0.0553, 0.4736, 0.4862, 0.2029,
          0.3475, 0.7099],
         [0.5867, 0.5003, 0.9311, 0.2697, 0.8449, 0.9514, 0.7759, 0.5126,
          0.5882, 0.4173],
         [0.7505, 0.6383, 0.1083, 0.2440, 0.1976, 0.7442, 0.5245, 0.4725,
          0.5005, 0.3722],
         [0.0922, 0.9980, 0.0323, 0.6492, 0.4018, 0.1920, 0.2985, 0.7140,
          0.1673,

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor.ndim, random_tensor.shape

(3, torch.Size([1, 3, 4]))

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244, 244, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim # Color channel may come infront

(torch.Size([244, 244, 3]), 3)

In [ ]:
torch.rand(size = (3,244,244))

tensor([[[0.5578, 0.5815, 0.9629,  ..., 0.1608, 0.4426, 0.1753],
         [0.8305, 0.5221, 0.8407,  ..., 0.1605, 0.0512, 0.4875],
         [0.8055, 0.1794, 0.4744,  ..., 0.1033, 0.0786, 0.8919],
         ...,
         [0.4233, 0.1972, 0.3097,  ..., 0.9500, 0.4268, 0.8070],
         [0.7136, 0.6327, 0.1528,  ..., 0.2307, 0.5385, 0.3519],
         [0.6049, 0.6667, 0.9452,  ..., 0.5685, 0.0165, 0.7566]],

        [[0.8268, 0.2672, 0.0167,  ..., 0.6586, 0.5173, 0.4556],
         [0.5075, 0.2489, 0.4606,  ..., 0.1792, 0.5812, 0.0247],
         [0.1282, 0.4666, 0.8843,  ..., 0.1663, 0.3064, 0.8965],
         ...,
         [0.2559, 0.3047, 0.2119,  ..., 0.7168, 0.9618, 0.8268],
         [0.1602, 0.0726, 0.9520,  ..., 0.3201, 0.6012, 0.6737],
         [0.9114, 0.5969, 0.4287,  ..., 0.6385, 0.7764, 0.2174]],

        [[0.3617, 0.0390, 0.5079,  ..., 0.9822, 0.9063, 0.0783],
         [0.5945, 0.5572, 0.8713,  ..., 0.8910, 0.6590, 0.6022],
         [0.6337, 0.1133, 0.2272,  ..., 0.6225, 0.5031, 0.

### Create a tensor of all zeors

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros* random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.rand()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# PyTorch & Numpy
Numpy is a popular scientific Python numerical computing library. Because of this, PyTorch has functionality ot interact with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`</br>
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3594, 0.3848, 0.3472, 0.2931],
        [0.2679, 0.7057, 0.9675, 0.3198],
        [0.9793, 0.8711, 0.0354, 0.5458]])
tensor([[0.3250, 0.1927, 0.7401, 0.7841],
        [0.7593, 0.7328, 0.4272, 0.6093],
        [0.0355, 0.3067, 0.5437, 0.6043]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Random Seed

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Three Different Ways to Access GPUs
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA + hardware + PyTorch working behind the scenes to make everything hunky dory (good).
### 1. Getting a GPU
1. Easies - Use Google Colab for a free GPU.
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS, Azure etc.

### 2. Check for GPU access with PyTorch

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Tue Aug 27 23:30:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Setup device agnostic code

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU reluts in faster computations

In [ ]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if availabe)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### Moving tensors back to cpu
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
# 4: 17: 58 Hour